services:
  db:
    image: postgis/postgis:16-3.4
    container_name: citistanbul_postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: citistanbul
      POSTGRES_PASSWORD: citistanbul
      POSTGRES_DB: citistanbul
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./data/interim:/import

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: citistanbul-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: citistanbul-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  postgis_data:
  es_data:
