services:
  db:
    image: postgis/postgis:16-3.4
    container_name: citistanbul_postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: citistanbul
      POSTGRES_PASSWORD: citistanbul
      POSTGRES_DB: citistanbul
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./data/interim:/import

volumes:
  postgis_data:
